"""empty message

Revision ID: de2c2e2e36f1
Revises: 58228692079b
Create Date: 2026-04-19 23:23:17.221809

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "de2c2e2e36f1"
down_revision = "58228692079b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("aubject", sa.String(), nullable=False))
        batch_op.drop_column("title")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("title", sa.VARCHAR(), nullable=False))
        batch_op.drop_column("aubject")

    # ### end Alembic commands ###
